"""Checked-in hull collision twin assets for conditional early-stop widen (#226).

Assets live under ``assets/analytics/scores/hull_collision_twins_{category}.yaml`` and are
regenerated by ``scripts/early_stop_hull_collisions.py --write-asset`` when priors or
component catalogs change. See design-military-score-build-inference-implementation.md
section 8.5.7.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

from api.analytics.scores_assets import Scores
from api.concepts.game_category import GameCategory

HULL_COLLISION_TWINS_VERSION = 1

TWIN_ASSET_CATEGORIES: tuple[GameCategory, ...] = (
    GameCategory.STANDARD,
    GameCategory.EPIC,
    GameCategory.CAMPAIGN,
)


@dataclass(frozen=True)
class HullCollisionTwinTriple:
    """Score-colliding low-tech / high-tech hull pair at one military change."""

    low_hull_id: int
    high_hull_id: int
    military_change: int


@dataclass(frozen=True)
class HullCollisionTwinPair:
    """Distinct low/high hull pair (diagnostics; no score filter)."""

    low_hull_id: int
    high_hull_id: int


@dataclass(frozen=True)
class HullCollisionTwinsProvenance:
    catalog_game_id: int
    catalog_host_turn: int
    catalog_perspective: int
    early_policy_step_id: str
    widen_hulls_policy_step_id: str
    early_stop_min_plausibility: int
    prior_asset_stem: str


@dataclass(frozen=True)
class HullCollisionTwinsAsset:
    category: GameCategory
    triples: tuple[HullCollisionTwinTriple, ...]
    pairs: tuple[HullCollisionTwinPair, ...]
    provenance: HullCollisionTwinsProvenance
    version: int = HULL_COLLISION_TWINS_VERSION


def twin_asset_filename(category: GameCategory) -> str:
    if category not in TWIN_ASSET_CATEGORIES:
        raise ValueError(
            f"hull collision twin assets are not defined for category {category.value!r}; "
            f"expected one of: {', '.join(c.value for c in TWIN_ASSET_CATEGORIES)}"
        )
    return f"hull_collision_twins_{category.value}.yaml"


def default_twin_assets_dir() -> Path:
    return Scores.assets_dir()


def default_twin_asset_path(
    category: GameCategory,
    *,
    base_dir: Path | None = None,
) -> Path:
    directory = default_twin_assets_dir() if base_dir is None else base_dir
    return directory / twin_asset_filename(category)


def twin_pairs_from_triples(
    triples: tuple[HullCollisionTwinTriple, ...] | list[HullCollisionTwinTriple],
) -> tuple[HullCollisionTwinPair, ...]:
    pairs = {
        (triple.low_hull_id, triple.high_hull_id): HullCollisionTwinPair(
            low_hull_id=triple.low_hull_id,
            high_hull_id=triple.high_hull_id,
        )
        for triple in triples
    }
    return tuple(
        pairs[key]
        for key in sorted(pairs)
    )


def build_twins_asset(
    *,
    category: GameCategory,
    triples: tuple[HullCollisionTwinTriple, ...] | list[HullCollisionTwinTriple],
    provenance: HullCollisionTwinsProvenance,
) -> HullCollisionTwinsAsset:
    unique_triples = tuple(
        sorted(
            {
                (t.low_hull_id, t.high_hull_id, t.military_change): t
                for t in triples
            }.values(),
            key=lambda t: (t.low_hull_id, t.high_hull_id, t.military_change),
        )
    )
    return HullCollisionTwinsAsset(
        category=category,
        triples=unique_triples,
        pairs=twin_pairs_from_triples(unique_triples),
        provenance=provenance,
    )


def twins_asset_to_document(asset: HullCollisionTwinsAsset) -> dict[str, Any]:
    return {
        "version": asset.version,
        "category": asset.category.value,
        "source": {
            "catalogGameId": asset.provenance.catalog_game_id,
            "catalogHostTurn": asset.provenance.catalog_host_turn,
            "catalogPerspective": asset.provenance.catalog_perspective,
            "earlyPolicyStepId": asset.provenance.early_policy_step_id,
            "widenHullsPolicyStepId": asset.provenance.widen_hulls_policy_step_id,
            "earlyStopMinPlausibility": asset.provenance.early_stop_min_plausibility,
            "priorAssetStem": asset.provenance.prior_asset_stem,
        },
        "triples": [
            {
                "lowHullId": triple.low_hull_id,
                "highHullId": triple.high_hull_id,
                "militaryChange": triple.military_change,
            }
            for triple in asset.triples
        ],
        "pairs": [
            {
                "lowHullId": pair.low_hull_id,
                "highHullId": pair.high_hull_id,
            }
            for pair in asset.pairs
        ],
    }


def _parse_int(raw: object, *, field_name: str) -> int:
    if not isinstance(raw, int):
        raise ValueError(f"hull collision twins {field_name} must be an int")
    return raw


def _parse_triples(raw: object) -> tuple[HullCollisionTwinTriple, ...]:
    if not isinstance(raw, list):
        raise ValueError("hull collision twins triples must be a list")
    triples: list[HullCollisionTwinTriple] = []
    for index, entry in enumerate(raw):
        if not isinstance(entry, dict):
            raise ValueError(f"hull collision twins triples[{index}] must be a mapping")
        triples.append(
            HullCollisionTwinTriple(
                low_hull_id=_parse_int(
                    entry.get("lowHullId"),
                    field_name=f"triples[{index}].lowHullId",
                ),
                high_hull_id=_parse_int(
                    entry.get("highHullId"),
                    field_name=f"triples[{index}].highHullId",
                ),
                military_change=_parse_int(
                    entry.get("militaryChange"),
                    field_name=f"triples[{index}].militaryChange",
                ),
            )
        )
    return tuple(triples)


def _parse_pairs(raw: object) -> tuple[HullCollisionTwinPair, ...]:
    if raw is None:
        return ()
    if not isinstance(raw, list):
        raise ValueError("hull collision twins pairs must be a list")
    pairs: list[HullCollisionTwinPair] = []
    for index, entry in enumerate(raw):
        if not isinstance(entry, dict):
            raise ValueError(f"hull collision twins pairs[{index}] must be a mapping")
        pairs.append(
            HullCollisionTwinPair(
                low_hull_id=_parse_int(
                    entry.get("lowHullId"),
                    field_name=f"pairs[{index}].lowHullId",
                ),
                high_hull_id=_parse_int(
                    entry.get("highHullId"),
                    field_name=f"pairs[{index}].highHullId",
                ),
            )
        )
    return tuple(pairs)


def _parse_provenance(raw: object) -> HullCollisionTwinsProvenance:
    if not isinstance(raw, dict):
        raise ValueError("hull collision twins source must be a mapping")
    prior_stem = raw.get("priorAssetStem")
    if not isinstance(prior_stem, str) or not prior_stem:
        raise ValueError("hull collision twins source.priorAssetStem must be a non-empty string")
    early_step = raw.get("earlyPolicyStepId")
    if not isinstance(early_step, str) or not early_step:
        raise ValueError("hull collision twins source.earlyPolicyStepId must be a non-empty string")
    widen_step = raw.get("widenHullsPolicyStepId")
    if not isinstance(widen_step, str) or not widen_step:
        raise ValueError(
            "hull collision twins source.widenHullsPolicyStepId must be a non-empty string"
        )
    return HullCollisionTwinsProvenance(
        catalog_game_id=_parse_int(
            raw.get("catalogGameId"),
            field_name="source.catalogGameId",
        ),
        catalog_host_turn=_parse_int(
            raw.get("catalogHostTurn"),
            field_name="source.catalogHostTurn",
        ),
        catalog_perspective=_parse_int(
            raw.get("catalogPerspective"),
            field_name="source.catalogPerspective",
        ),
        early_policy_step_id=early_step,
        widen_hulls_policy_step_id=widen_step,
        early_stop_min_plausibility=_parse_int(
            raw.get("earlyStopMinPlausibility"),
            field_name="source.earlyStopMinPlausibility",
        ),
        prior_asset_stem=prior_stem,
    )


def parse_hull_collision_twins_document(document: dict[str, Any]) -> HullCollisionTwinsAsset:
    version = document.get("version")
    if version != HULL_COLLISION_TWINS_VERSION:
        raise ValueError(
            f"hull collision twins version must be {HULL_COLLISION_TWINS_VERSION}, got {version!r}"
        )
    category_raw = document.get("category")
    if not isinstance(category_raw, str):
        raise ValueError("hull collision twins category must be a string")
    try:
        category = GameCategory(category_raw)
    except ValueError as exc:
        raise ValueError(f"unknown hull collision twins category {category_raw!r}") from exc
    if category not in TWIN_ASSET_CATEGORIES:
        raise ValueError(f"unsupported hull collision twins category {category.value!r}")

    triples = _parse_triples(document.get("triples"))
    pairs = _parse_pairs(document.get("pairs"))
    if not pairs:
        pairs = twin_pairs_from_triples(triples)
    else:
        expected = set(twin_pairs_from_triples(triples))
        actual = set(pairs)
        if actual != expected:
            raise ValueError(
                "hull collision twins pairs must match the distinct (lowHullId, highHullId) "
                "set derived from triples"
            )
        pairs = twin_pairs_from_triples(triples)

    return HullCollisionTwinsAsset(
        category=category,
        triples=tuple(
            sorted(triples, key=lambda t: (t.low_hull_id, t.high_hull_id, t.military_change))
        ),
        pairs=pairs,
        provenance=_parse_provenance(document.get("source")),
        version=HULL_COLLISION_TWINS_VERSION,
    )


def load_hull_collision_twins_asset(path: Path) -> HullCollisionTwinsAsset:
    with path.open(encoding="utf-8") as handle:
        document = yaml.safe_load(handle)
    if not isinstance(document, dict):
        raise ValueError(f"hull collision twins root must be a mapping: {path}")
    asset = parse_hull_collision_twins_document(document)
    expected_stem = Path(twin_asset_filename(asset.category)).stem
    if path.stem != expected_stem:
        raise ValueError(
            f"hull collision twins path stem {path.stem!r} does not match category "
            f"{asset.category.value!r} (expected {expected_stem!r})"
        )
    return asset


def load_hull_collision_twins_for_category(
    category: GameCategory,
    *,
    base_dir: Path | None = None,
) -> tuple[HullCollisionTwinsAsset, Path]:
    path = default_twin_asset_path(category, base_dir=base_dir)
    return load_hull_collision_twins_asset(path), path


def write_hull_collision_twins_asset(path: Path, asset: HullCollisionTwinsAsset) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    document = twins_asset_to_document(asset)
    header = (
        "# Hull collision twins for conditional early-stop widen (#226).\n"
        "# Prefer (lowHullId, highHullId, militaryChange) triples over bare pairs so a\n"
        "# Valiant@2749 admit Resolute without every Dark Wing twin that only collides at 3281.\n"
        "#\n"
        "# Regenerate (priors / catalogs changed):\n"
        "#   uv run python scripts/early_stop_hull_collisions.py \\\n"
        f"#     --game-type {asset.category.value} --write-asset\n"
        "# Optional: --game-id / --host-turn / --storage-root / --asset-dir\n"
        "#\n"
    )
    body = yaml.safe_dump(
        document,
        sort_keys=False,
        default_flow_style=False,
        allow_unicode=True,
    )
    path.write_text(header + body, encoding="utf-8")
    return path
