/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Analytics
         * @description Return analytics available to the console (placeholder list).
         */
        get: operations["list_analytics_analytics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/{analytic_id}/table": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analytic Table
         * @description Placeholder tabular data (scoped for cache invalidation; same shape for now).
         */
        get: operations["get_analytic_table_analytics__analytic_id__table_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/{analytic_id}/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analytic Map
         * @description Map data (nodes/edges). Base map = planets + connections; selectable analytics add overlays.
         *
         *     Nodes use fixed Cartesian coordinates (x, y). Base map is always fetched first;
         *     selectable analytics contribute extra nodes/edges or (later) highlights.
         */
        get: operations["get_analytic_map_analytics__analytic_id__map_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Stored Games
         * @description Return game ids present under store path `games` (next-hop segment names).
         *
         *     Route: **GET /games** on the BFF app; **GET /bff/games** when the BFF is mounted at `/bff`.
         *
         *     Uses the same shallow enumeration as GET /api/v1/store/games?view=shallow.
         */
        get: operations["list_stored_games_games_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stored Game Info
         * @description Return game info already in storage (no Planets.nu refresh).
         */
        get: operations["get_stored_game_info_games__game_id__info_get"];
        put?: never;
        /**
         * Post Game Info
         * @description Refresh game info from Planets.nu (`refresh`); returns updated `GameInfo`.
         */
        post: operations["post_game_info_games__game_id__info_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/turns/ensure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Ensure Turn
         * @description Ensure turn data exists in storage; fetch from Planets.nu when absent.
         */
        post: operations["post_ensure_turn_games__game_id__turns_ensure_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/{perspective}/turns/{turn_number}/concepts/warp-wells/coordinate-in-well": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Warp Well Coordinate In Well
         * @description Shallow forward to Core ``GameService`` (same contract as Core REST).
         */
        post: operations["post_warp_well_coordinate_in_well_games__game_id___perspective__turns__turn_number__concepts_warp_wells_coordinate_in_well_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/{perspective}/turns/{turn_number}/concepts/warp-wells/cells": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Warp Well Cells
         * @description Shallow forward to Core ``GameService`` (same contract as Core REST).
         */
        get: operations["get_warp_well_cells_games__game_id___perspective__turns__turn_number__concepts_warp_wells_cells_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shell/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Shell Bootstrap
         * @description Return shell-oriented server config for the SPA (e.g. optional default game id).
         */
        get: operations["get_shell_bootstrap_shell_bootstrap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CoordinateInWarpWellRequest */
        CoordinateInWarpWellRequest: {
            /** Planet Id */
            planet_id: number;
            /** Map X */
            map_x: number;
            /** Map Y */
            map_y: number;
            well_type: components["schemas"]["WarpWellTypeParam"];
        };
        /** CoordinateInWarpWellResponse */
        CoordinateInWarpWellResponse: {
            /** Inside */
            inside: boolean;
        };
        /**
         * FlareConnectionMode
         * @description How flare-assisted routes are combined with direct warp-well reachability.
         * @enum {string}
         */
        FlareConnectionMode: "off" | "include" | "only";
        /** Game */
        Game: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Shortdescription */
            shortdescription: string;
            status: components["schemas"]["GameStatus"];
            /** Datecreated */
            datecreated: string;
            /** Dateended */
            dateended: string;
            /** Maptype */
            maptype: number;
            /** Gametype */
            gametype: number;
            /** Wincondition */
            wincondition: number;
            /** Difficulty */
            difficulty: number;
            /** Tutorialid */
            tutorialid: number;
            /** Requiredlevelid */
            requiredlevelid: number;
            /** Maxlevelid */
            maxlevelid: number;
            /** Masterplanetid */
            masterplanetid: number;
            /** Quadrant */
            quadrant: number;
            /** Mintenacity */
            mintenacity: number;
            /** Faststart */
            faststart: number;
            /** Turnsperweek */
            turnsperweek: number;
            /** Yearstarted */
            yearstarted: number;
            /** Isprivate */
            isprivate: boolean;
            /** Scenarioid */
            scenarioid: number;
            /** Createdby */
            createdby: string;
            /** Turn */
            turn: number;
            /** Slots */
            slots: number;
            /** Turnstatus */
            turnstatus: string;
            /** Hostdays */
            hostdays: string;
            /** Slowhostdays */
            slowhostdays: string;
            /** Hosttime */
            hosttime: string;
            /** Lastbackuppath */
            lastbackuppath: string;
            /** Nexthost */
            nexthost: string;
            /** Allturnsin */
            allturnsin: boolean;
            /** Lastnotified */
            lastnotified: boolean;
            /** Ishosting */
            ishosting: boolean;
            /** Lastloadeddate */
            lastloadeddate: string;
            /** Deletedate */
            deletedate: string;
            /** Lasthostdate */
            lasthostdate: string;
            /** Password */
            password: string;
            /** Groups */
            groups: string;
            /** Leagueseason */
            leagueseason: number;
            /** Leaguetier */
            leaguetier: number;
            /** Leaguegametype */
            leaguegametype: number;
            /** Haspassword */
            haspassword: boolean;
            /** Statusname */
            statusname: string;
            /** Justended */
            justended: boolean;
            /** Iscustom */
            iscustom: boolean;
            /** Timetohostshort */
            timetohostshort: string;
            /** Timetohost */
            timetohost: string;
        };
        /** GameInfo */
        GameInfo: {
            game: components["schemas"]["Game"];
            /** Players */
            players: components["schemas"]["Player"][];
            /** Relations */
            relations: components["schemas"]["Relation"][];
            settings: components["schemas"]["GameSettings"];
            /** Schedule */
            schedule: string;
            /** Timetohost */
            timetohost: string;
            /** Wincondition */
            wincondition: string;
            /** Yearfrom */
            yearfrom?: number | null;
            /** Yearto */
            yearto?: number | null;
        };
        /**
         * GameInfoUpdateOperation
         * @enum {string}
         */
        GameInfoUpdateOperation: "refresh";
        /** GameInfoUpdateRequest */
        GameInfoUpdateRequest: {
            operation: components["schemas"]["GameInfoUpdateOperation"];
            /** Params */
            params: {
                [key: string]: unknown;
            };
        };
        /** GameSettings */
        GameSettings: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Turn */
            turn: number;
            /** Buildqueueplanetid */
            buildqueueplanetid: number;
            /** Victorycountdown */
            victorycountdown: number;
            /** Maxallies */
            maxallies: number;
            /** Maxshareintel */
            maxshareintel: number;
            /** Maxsafepassage */
            maxsafepassage: number;
            /** Alliessharefullinfo */
            alliessharefullinfo: boolean;
            /** Mapwidth */
            mapwidth: number;
            /** Mapheight */
            mapheight: number;
            /** Numplanets */
            numplanets: number;
            /** Shiplimit */
            shiplimit: number;
            /** Hoststart */
            hoststart: string;
            /** Hostcompleted */
            hostcompleted: string;
            /** Nexthost */
            nexthost: string;
            /** Lastinvite */
            lastinvite: string;
            /** Teamsize */
            teamsize: number;
            /** Planetscanrange */
            planetscanrange: number;
            /** Shipscanrange */
            shipscanrange: number;
            /** Allvisible */
            allvisible: boolean;
            /** Minefieldsvisible */
            minefieldsvisible: boolean;
            /** Allplanetsvisible */
            allplanetsvisible: boolean;
            /** Planetownershipvisible */
            planetownershipvisible: boolean;
            /** Starbasesvisible */
            starbasesvisible: boolean;
            /** Shipsatplanetsvisible */
            shipsatplanetsvisible: boolean;
            /** Noreducedpodscanrange */
            noreducedpodscanrange: boolean;
            /** Allnormalscannedshipsvisible */
            allnormalscannedshipsvisible: boolean;
            /** Oneseesshipallseeship */
            oneseesshipallseeship: boolean;
            /** Spectatormode */
            spectatormode: boolean;
            /** Allshareintel */
            allshareintel: boolean;
            /** Nebulas */
            nebulas: number;
            /** Stars */
            stars: number;
            /** Neutrinostars */
            neutrinostars: number;
            /** Blackholes */
            blackholes: number;
            /** Maxwormholes */
            maxwormholes: number;
            /** Wormholemix */
            wormholemix: number;
            /** Wormholescanrange */
            wormholescanrange: number;
            /** Discussionid */
            discussionid: string;
            /** Nuionstorms */
            nuionstorms: boolean;
            /** Maxions */
            maxions: number;
            /** Maxioncloudsperstorm */
            maxioncloudsperstorm: number;
            /** Debrisdiskpercent */
            debrisdiskpercent: number;
            /** Debrisdiskversion */
            debrisdiskversion: number;
            /** Cloakfail */
            cloakfail: number;
            /** Structuredecayrate */
            structuredecayrate: number;
            /** Mapshape */
            mapshape: number;
            /** Verycloseplanets */
            verycloseplanets: number;
            /** Closeplanets */
            closeplanets: number;
            /** Nextplanets */
            nextplanets: number;
            /** Otherplanetsminhomeworlddist */
            otherplanetsminhomeworlddist: number;
            /** Ncircles */
            ncircles: number;
            /** Hwdistribution */
            hwdistribution: number;
            /** Ndebrisdiscs */
            ndebrisdiscs: number;
            /** Balanceadjustment */
            balanceadjustment: number;
            /** Closeplanetrangeinc */
            closeplanetrangeinc: number;
            /** Levelid */
            levelid: number;
            /** Nextlevelid */
            nextlevelid: number;
            /** Storyid */
            storyid: number;
            /** Killrace */
            killrace: boolean;
            /** Runningstart */
            runningstart: number;
            /** Deadradius */
            deadradius: number;
            /** Playerselectrace */
            playerselectrace: boolean;
            /** Militaryscorepercent */
            militaryscorepercent: number;
            /** Hideraceselection */
            hideraceselection: boolean;
            /** Hideplayerselection */
            hideplayerselection: boolean;
            /** Fixedstartpositions */
            fixedstartpositions: boolean;
            /** Shuffleteampositions */
            shuffleteampositions: boolean;
            /** Interestsignup */
            interestsignup: boolean;
            /** Interestsignupracecount */
            interestsignupracecount: number;
            /** Minnativeclans */
            minnativeclans: number;
            /** Maxnativeclans */
            maxnativeclans: number;
            /** Nohomeworld */
            nohomeworld: boolean;
            /** Homeworldhasstarbase */
            homeworldhasstarbase: boolean;
            /** Homeworldclans */
            homeworldclans: number;
            /** Homeworldresources */
            homeworldresources: number;
            /** Hwlosthappinesslosscolonists */
            hwlosthappinesslosscolonists: number;
            /** Hwlosthappinesslossnatives */
            hwlosthappinesslossnatives: number;
            /** Gamepassword */
            gamepassword: string;
            /** Extraplanets */
            extraplanets: number;
            /** Extraships */
            extraships: number;
            /** Centerextraplanets */
            centerextraplanets: number;
            /** Centerextraships */
            centerextraships: number;
            /** Extraplanetsrandomloc */
            extraplanetsrandomloc: boolean;
            /** Extrashipsrandomloc */
            extrashipsrandomloc: boolean;
            /** Wanderingtribescount */
            wanderingtribescount: number;
            /** Wanderingtribesdist */
            wanderingtribesdist: number;
            /** Neutroniumlevel */
            neutroniumlevel: number;
            /** Duraniumlevel */
            duraniumlevel: number;
            /** Tritaniumlevel */
            tritaniumlevel: number;
            /** Molybdenumlevel */
            molybdenumlevel: number;
            /** Averagedensitypercent */
            averagedensitypercent: number;
            /** Developmentfactor */
            developmentfactor: number;
            /** Nativeprobability */
            nativeprobability: number;
            /** Nativegovernmentlevel */
            nativegovernmentlevel: number;
            /** Neusurfacemax */
            neusurfacemax: number;
            /** Dursurfacemax */
            dursurfacemax: number;
            /** Trisurfacemax */
            trisurfacemax: number;
            /** Molsurfacemax */
            molsurfacemax: number;
            /** Neugroundmax */
            neugroundmax: number;
            /** Durgroundmax */
            durgroundmax: number;
            /** Trigroundmax */
            trigroundmax: number;
            /** Molgroundmax */
            molgroundmax: number;
            /** Planetlevelmax */
            planetlevelmax: number;
            /** Computerbuildships */
            computerbuildships: boolean;
            /** Computerbuilddelay */
            computerbuilddelay: number;
            /** Computerreplacedrops */
            computerreplacedrops: boolean;
            /** Bringhomesectorships */
            bringhomesectorships: boolean;
            /** Homesectorshipvaluemin */
            homesectorshipvaluemin: number;
            /** Homesectorshipvaluemax */
            homesectorshipvaluemax: number;
            /** Entryportalplayers */
            entryportalplayers: string;
            /** Reinforcementsallowed */
            reinforcementsallowed: boolean;
            /** Fightorfail */
            fightorfail: number;
            /** Fofactiveturn */
            fofactiveturn: number;
            /** Fofincrement */
            fofincrement: number;
            /** Fofaccelrate */
            fofaccelrate: number;
            /** Fofaccelstartturn */
            fofaccelstartturn: number;
            /** Fofaccelstartdate */
            fofaccelstartdate: string;
            /** Fofbyteam */
            fofbyteam: boolean;
            /** Meteorshowerchance */
            meteorshowerchance: number;
            /** Computerplayerrangelimitation */
            computerplayerrangelimitation: number;
            /** Stealthmode */
            stealthmode: boolean;
            /** Sphere */
            sphere: boolean;
            /** Showallexplosions */
            showallexplosions: boolean;
            /** Highidfixchunnelusepodhullid */
            highidfixchunnelusepodhullid: boolean;
            /** Highidfixfightertransferoffset */
            highidfixfightertransferoffset: number;
            /** Nochunnelhives */
            nochunnelhives: boolean;
            /** Mining200Adjustment */
            mining200adjustment: number;
            /** Freestarbasefighters5Adjustment */
            freestarbasefighters5adjustment: number;
            /** Cyborgmaxnativetaxrateadjustment */
            cyborgmaxnativetaxrateadjustment: number;
            /** Assimilationrateadjustment */
            assimilationrateadjustment: number;
            /** Maxhissersperplanet */
            maxhissersperplanet: number;
            /** Chunnelstabilizationeverywhere */
            chunnelstabilizationeverywhere: boolean;
            /** Groundattackadjustments */
            groundattackadjustments: string;
            /** Colonisttaxrateadjustments */
            colonisttaxrateadjustments: string;
            /** Nativetaxrateadjustments */
            nativetaxrateadjustments: string;
            /** Campaignmode */
            campaignmode: boolean;
            /** Maxadvantage */
            maxadvantage: number;
            /** Fascistdoublebeams */
            fascistdoublebeams: boolean;
            /** Starbasefightertransfer */
            starbasefightertransfer: boolean;
            /** Superspyadvanced */
            superspyadvanced: boolean;
            /** Cloakandintercept */
            cloakandintercept: boolean;
            /** Quantumtorpedos */
            quantumtorpedos: boolean;
            /** Galacticpower */
            galacticpower: boolean;
            /** Hardenedmines */
            hardenedmines: boolean;
            /** Racehullsonlyfascistdoublebeams */
            racehullsonlyfascistdoublebeams: boolean;
            /** Racehullsonlycloakandintercept */
            racehullsonlycloakandintercept: boolean;
            /** Racehullsonlyhiss */
            racehullsonlyhiss: boolean;
            /** Repairshipreplacessagefrigate */
            repairshipreplacessagefrigate: boolean;
            /** Migtransportreplacesmigscout */
            migtransportreplacesmigscout: boolean;
            /** Saurianlightfrigatereplacessaurian */
            saurianlightfrigatereplacessaurian: boolean;
            /** Scorpiuscarrierreplacesscorpiuslight */
            scorpiuscarrierreplacesscorpiuslight: boolean;
            /** Sscruiseriireplacessscruiser */
            sscruiseriireplacessscruiser: boolean;
            /** Sscarrierplusreplacessscarrier */
            sscarrierplusreplacessscarrier: boolean;
            /** Skyfireplusreplacesskyfire */
            skyfireplusreplacesskyfire: boolean;
            /** D7Creplacesd7A */
            d7creplacesd7a: boolean;
            /** Quietusplusreplacesquietus */
            quietusplusreplacesquietus: boolean;
            /** Cybernautlightreplacescybernaut */
            cybernautlightreplacescybernaut: boolean;
            /** Birdshaveenlighten */
            birdshaveenlighten: boolean;
            /** Sscruiserinterceptinterference */
            sscruiserinterceptinterference: boolean;
            /** Moscowinterceptinterference */
            moscowinterceptinterference: boolean;
            /** Sapphirenowebimmunity */
            sapphirenowebimmunity: boolean;
            /** Destroyplanetcausesfear */
            destroyplanetcausesfear: boolean;
            /** Quantumtorpedomissrateforgravitonics */
            quantumtorpedomissrateforgravitonics: number;
            /** Torpedomissrateforsinglegunboats */
            torpedomissrateforsinglegunboats: number;
            /** Elusivefighterdefense */
            elusivefighterdefense: number;
            /** Fedfrigatefighterdefense */
            fedfrigatefighterdefense: number;
            /** Scoutsplanetimmunity */
            scoutsplanetimmunity: boolean;
            /** Hrossfightertransfer */
            hrossfightertransfer: boolean;
            /** Empirehasaggregator */
            empirehasaggregator: boolean;
            /** Fighterfactoryshipset */
            fighterfactoryshipset: number;
            /** Ironslavescoutreplacesironslave */
            ironslavescoutreplacesironslave: boolean;
            /** Diplomaticspiesnoambassador */
            diplomaticspiesnoambassador: boolean;
            /** Simplestealtharmordist */
            simplestealtharmordist: number;
            /** Simplestealtharmorsensorswwepdist */
            simplestealtharmorsensorswwepdist: number;
            /** Torpedoset */
            torpedoset: number;
            /** Shiplimittype */
            shiplimittype: number;
            /** Plsminships */
            plsminships: number;
            /** Plsextraships */
            plsextraships: number;
            /** Plsshipsperplanet */
            plsshipsperplanet: number;
            /** Productionqueue */
            productionqueue: boolean;
            /** Productionbasecost */
            productionbasecost: number;
            /** Productionstarbaseoutput */
            productionstarbaseoutput: number;
            /** Productionstarbasereward */
            productionstarbasereward: number;
            /** Productionsmallshipset */
            productionsmallshipset: number;
            /** Planetaryproductionqueue */
            planetaryproductionqueue: boolean;
            /** Fcodesrbx */
            fcodesrbx: boolean;
            /** Ppqminbuilds */
            ppqminbuilds: number;
            /** Endturn */
            endturn: number;
            /** Alwaysuseendturn */
            alwaysuseendturn: boolean;
            /** Maxplayersperrace */
            maxplayersperrace: number;
            /** Nowebfriendlycodes */
            nowebfriendlycodes: boolean;
            /** Nowebsinotherids */
            nowebsinotherids: boolean;
            /** Webdiplomacylevel */
            webdiplomacylevel: number;
            /** Webdraindiplomacylevel */
            webdraindiplomacylevel: number;
            /** Crystalwebimmunity */
            crystalwebimmunity: number;
            /** Fcodesmustmatchgsx */
            fcodesmustmatchgsx: boolean;
            /** Fcodesextraalchemy */
            fcodesextraalchemy: boolean;
            /** Fcodesbdx */
            fcodesbdx: boolean;
            /** Fcodesnogsx */
            fcodesnogsx: boolean;
            /** Fcodesnomix */
            fcodesnomix: boolean;
            /** Cloningenabled */
            cloningenabled: boolean;
            /** Supertransportfuelmod */
            supertransportfuelmod: number;
            /** Unlimitedfuel */
            unlimitedfuel: boolean;
            /** Unlimitedammo */
            unlimitedammo: boolean;
            /** Nominefields */
            nominefields: boolean;
            /** Nosupplies */
            nosupplies: boolean;
            /** Nowarpwells */
            nowarpwells: boolean;
            /** Directtransfermc */
            directtransfermc: boolean;
            /** Directtransferammo */
            directtransferammo: boolean;
            /** Transferoverloadprioritizeammo */
            transferoverloadprioritizeammo: boolean;
            /** Topadvancecount */
            topadvancecount: number;
            /** Snapgridsize */
            snapgridsize: number;
            /** Dumppartsdumpstorps */
            dumppartsdumpstorps: boolean;
            /** Burrowsimprovemining */
            burrowsimprovemining: boolean;
            /** Horwaspfighterlossclankill */
            horwaspfighterlossclankill: number;
            /** Hivesdetectlife */
            hivesdetectlife: boolean;
            /** Sensorsweepcombatpodscanrange */
            sensorsweepcombatpodscanrange: number;
            /** Sensorsweepnoncombatpodscanrange */
            sensorsweepnoncombatpodscanrange: number;
            /** Horwaspscanrobotmodifier */
            horwaspscanrobotmodifier: number;
            /** Isacademy */
            isacademy: boolean;
            /** Acceleratedturns */
            acceleratedturns: number;
            /** Disallowedraces */
            disallowedraces: string;
            /** Emorkslegacy */
            emorkslegacy: boolean;
            /** Combatrng */
            combatrng: number;
            /** Chainedintercept */
            chainedintercept: boolean;
            /** Randomplayerslots */
            randomplayerslots: boolean;
            /** Presethulls */
            presethulls: boolean;
            /** Presethullsbyrace */
            presethullsbyrace: string;
            /** Presetadvantages */
            presetadvantages: boolean;
            /** Orderedgroupjoindays */
            orderedgroupjoindays: number;
            /** Joininggroupindex */
            joininggroupindex: number;
            /** Aicanchangediplomacy */
            aicanchangediplomacy: boolean;
            /** Defensepostsblocksensorsweep */
            defensepostsblocksensorsweep: boolean;
            /** Victoryscorepointsneededsolo */
            victoryscorepointsneededsolo: number;
            /** Victoryscorepointsneededally */
            victoryscorepointsneededally: number;
            /** Victoryscorepointsperplanet */
            victoryscorepointsperplanet: number;
            /** Victoryscorepointsperstarbase */
            victoryscorepointsperstarbase: number;
            /** Victoryscorepointsperhighpop */
            victoryscorepointsperhighpop: number;
            /** Victoryscoreclansforhighpop */
            victoryscoreclansforhighpop: number;
            /** Victoryscorepointsperbonus */
            victoryscorepointsperbonus: number;
            /** Victoryscorebonusdetails */
            victoryscorebonusdetails: boolean;
        };
        /**
         * GameStatus
         * @enum {integer}
         */
        GameStatus: -1 | 0 | 1 | 2 | 3;
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MapCellModel */
        MapCellModel: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** Player */
        Player: {
            /** Id */
            id: number;
            /** Status */
            status: number;
            /** Statusturn */
            statusturn: number;
            /** Accountid */
            accountid: number;
            /** Username */
            username: string;
            /** Email */
            email: string;
            /** Raceid */
            raceid: number;
            /** Teamid */
            teamid: number;
            /** Prioritypoints */
            prioritypoints: number;
            /** Joinrank */
            joinrank: number;
            /** Finishrank */
            finishrank: number;
            /** Turnjoined */
            turnjoined: number;
            /** Turnready */
            turnready: boolean;
            /** Turnreadydate */
            turnreadydate: string;
            /** Turnstatus */
            turnstatus: number;
            /** Turnsmissed */
            turnsmissed: number;
            /** Turnsmissedtotal */
            turnsmissedtotal: number;
            /** Turnsholiday */
            turnsholiday: number;
            /** Turnsearly */
            turnsearly: number;
            /** Turn */
            turn: number;
            /** Timcontinuum */
            timcontinuum: number;
            /** Savekey */
            savekey: string;
            /** Tutorialid */
            tutorialid: number;
            /** Tutorialtaskid */
            tutorialtaskid: number;
            /** Megacredits */
            megacredits: number;
            /** Duranium */
            duranium: number;
            /** Tritanium */
            tritanium: number;
            /** Molybdenum */
            molybdenum: number;
            /** Leagueteamid */
            leagueteamid: number;
            /** Activehulls */
            activehulls: string;
            /** Activeadvantages */
            activeadvantages: string;
            /** Activeengines */
            activeengines: string;
            /** Activebeams */
            activebeams: string;
            /** Activetorps */
            activetorps: string;
        };
        /** Relation */
        Relation: {
            /** Id */
            id: number;
            /** Playerid */
            playerid: number;
            /** Playertoid */
            playertoid: number;
            /** Relationto */
            relationto: number;
            /** Relationfrom */
            relationfrom: number;
            /** Conflictlevel */
            conflictlevel: number;
            /** Color */
            color: string;
        };
        /** ShellBootstrapResponse */
        ShellBootstrapResponse: {
            /**
             * Showinitialgame
             * @description Stored game id to load automatically without login, or null when disabled.
             */
            showInitialGame?: string | null;
        };
        /**
         * TurnEnsureRequest
         * @description Parameters to ensure turn data exists in storage for a game and perspective slot.
         */
        TurnEnsureRequest: {
            /** Turn */
            turn: number;
            /** Perspective */
            perspective: number;
            /**
             * Username
             * @description Planets.nu account; required only when turn data is missing from storage and must be loaded from upstream.
             * @default
             */
            username: string;
            /** Password */
            password?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WarpWellCellsResponse */
        WarpWellCellsResponse: {
            /** Cells */
            cells: components["schemas"]["MapCellModel"][];
        };
        /**
         * WarpWellTypeParam
         * @enum {string}
         */
        WarpWellTypeParam: "normal" | "hyperjump";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_analytics_analytics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_analytic_table_analytics__analytic_id__table_get: {
        parameters: {
            query: {
                gameId: number;
                turn: number;
                perspective: number;
            };
            header?: never;
            path: {
                analytic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analytic_map_analytics__analytic_id__map_get: {
        parameters: {
            query: {
                gameId: number;
                turn: number;
                perspective: number;
                warpSpeed?: number;
                gravitonicMovement?: boolean;
                flareMode?: components["schemas"]["FlareConnectionMode"];
            };
            header?: never;
            path: {
                analytic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stored_games_games_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_stored_game_info_games__game_id__info_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_game_info_games__game_id__info_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GameInfoUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_ensure_turn_games__game_id__turns_ensure_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnEnsureRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_warp_well_coordinate_in_well_games__game_id___perspective__turns__turn_number__concepts_warp_wells_coordinate_in_well_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: number;
                perspective: number;
                turn_number: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoordinateInWarpWellRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoordinateInWarpWellResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_warp_well_cells_games__game_id___perspective__turns__turn_number__concepts_warp_wells_cells_get: {
        parameters: {
            query: {
                planet_id: number;
                well_type: components["schemas"]["WarpWellTypeParam"];
            };
            header?: never;
            path: {
                game_id: number;
                perspective: number;
                turn_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WarpWellCellsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shell_bootstrap_shell_bootstrap_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShellBootstrapResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
