/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Stored Games
         * @description Return stored game ids (optional sector names) via Core ``GameService``.
         *
         *     Route: **GET /games** on the BFF app; **GET /bff/games** when mounted at `/bff`.
         */
        get: operations["list_stored_games_games_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/turns/{turn_number}/stored-perspectives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stored Turn Perspectives
         * @description Return perspective slots that already have turn data in storage (no Planets.nu).
         */
        get: operations["get_stored_turn_perspectives_games__game_id__turns__turn_number__stored_perspectives_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stored Game Info
         * @description Return game info already in storage (no Planets.nu refresh).
         */
        get: operations["get_stored_game_info_games__game_id__info_get"];
        put?: never;
        /**
         * Post Game Info
         * @description Refresh game info from Planets.nu (`refresh`); returns updated `GameInfo`.
         */
        post: operations["post_game_info_games__game_id__info_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/turns/load-all-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Load All Turns Status
         * @description Whether storage already has every turn expected after a bulk load.
         */
        get: operations["get_load_all_turns_status_games__game_id__turns_load_all_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/turns/load-all/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Load All Turns Stream
         * @description Load all turns, streaming NDJSON progress events.
         */
        post: operations["post_load_all_turns_stream_games__game_id__turns_load_all_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/turns/ensure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Ensure Turn
         * @description Ensure turn data exists in storage; fetch from Planets.nu when absent.
         */
        post: operations["post_ensure_turn_games__game_id__turns_ensure_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/{perspective}/turns/{turn_number}/concepts/warp-wells/coordinate-in-well": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Warp Well Coordinate In Well
         * @description Turn-scoped warp-well point test via ``CoreClient`` (shared handler with Core REST).
         */
        post: operations["post_warp_well_coordinate_in_well_games__game_id___perspective__turns__turn_number__concepts_warp_wells_coordinate_in_well_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/{perspective}/turns/{turn_number}/concepts/warp-wells/cells": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Warp Well Cells
         * @description Turn-scoped warp-well cells via ``CoreClient`` (shared handler with Core REST).
         */
        get: operations["get_warp_well_cells_games__game_id___perspective__turns__turn_number__concepts_warp_wells_cells_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/{perspective}/turns/{turn_number}/concepts/stellar-cartography/sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stellar Cartography Sample
         * @description Turn-scoped Stellar Cartography cell sample via ``CoreClient``.
         */
        get: operations["get_stellar_cartography_sample_games__game_id___perspective__turns__turn_number__concepts_stellar_cartography_sample_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/{perspective}/turns/{turn_number}/concepts/stellar-cartography/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stellar Cartography Turn Summary
         * @description Turn-scoped lightweight Stellar Cartography facts via ``CoreClient``.
         */
        get: operations["get_stellar_cartography_turn_summary_games__game_id___perspective__turns__turn_number__concepts_stellar_cartography_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BffGameInfoResponse: unknown;
        BffTurnInfoResponse: unknown;
        /** CoordinateInWarpWellRequest */
        CoordinateInWarpWellRequest: {
            /** Planet Id */
            planet_id: number;
            /** Map X */
            map_x: number;
            /** Map Y */
            map_y: number;
            well_type: components["schemas"]["WarpWellTypeParam"];
        };
        /** CoordinateInWarpWellResponse */
        CoordinateInWarpWellResponse: {
            /** Inside */
            inside: boolean;
        };
        /**
         * GameInfoUpdateOperation
         * @enum {string}
         */
        GameInfoUpdateOperation: "refresh";
        /** GameInfoUpdateRequest */
        GameInfoUpdateRequest: {
            operation: components["schemas"]["GameInfoUpdateOperation"];
            /** Params */
            params: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoadAllStreamCompleteEvent
         * @description Final NDJSON line after bulk load (``type: complete``).
         */
        LoadAllStreamCompleteEvent: {
            /**
             * Type
             * @constant
             */
            type: "complete";
            result: components["schemas"]["LoadAllTurnsResponse"];
        };
        /**
         * LoadAllStreamErrorEvent
         * @description NDJSON line when bulk load fails (``type: error``).
         */
        LoadAllStreamErrorEvent: {
            /**
             * Type
             * @constant
             */
            type: "error";
            /** Detail */
            detail: string;
        };
        /**
         * LoadAllStreamProgressEvent
         * @description One NDJSON line while bulk-loading turns (``type: progress``).
         */
        LoadAllStreamProgressEvent: {
            /**
             * Phase
             * @enum {string}
             */
            phase: "download" | "import" | "final_turn";
            /**
             * Perspective
             * @description 1-based perspective index; 0 during download.
             */
            perspective: number;
            /** Perspective Total */
            perspective_total: number;
            /**
             * Turn
             * @description 1-based turn step within the current perspective.
             */
            turn: number;
            /** Turn Total */
            turn_total: number;
            /**
             * Message
             * @default
             */
            message: string;
            /**
             * Type
             * @constant
             */
            type: "progress";
        };
        /** LoadAllTurnsRequest */
        LoadAllTurnsRequest: {
            /**
             * Username
             * @description Non-empty required for refresh; ensure-turn may omit when data is local.
             * @default
             */
            username: string;
            /** Password */
            password?: string | null;
        };
        /** LoadAllTurnsResponse */
        LoadAllTurnsResponse: {
            /** Game Id */
            game_id: number;
            /** Is Game Finished */
            is_game_finished: boolean;
            /** Turns Written */
            turns_written: number;
            /** Turns Skipped */
            turns_skipped: number;
            /** Perspectives Touched */
            perspectives_touched?: number[];
            /**
             * Final Turn Load Failures
             * @description 1-based perspective slots where the final turn could not be fetched via loadturn after a finished-game loadall archive import.
             */
            final_turn_load_failures?: number[];
        };
        /** LoadAllTurnsStatusResponse */
        LoadAllTurnsStatusResponse: {
            /** Game Id */
            game_id: number;
            /** Complete */
            complete: boolean;
            /** Is Game Finished */
            is_game_finished: boolean;
            /** Expected Perspectives */
            expected_perspectives?: number[];
            /** Latest Turn */
            latest_turn: number;
        };
        /** MapCellModel */
        MapCellModel: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** StellarCartographySampleEntry */
        StellarCartographySampleEntry: {
            /**
             * Layer
             * @enum {string}
             */
            layer: "debris-disks" | "nebulae" | "ion-storms" | "star-clusters" | "neutron-clusters" | "black-holes" | "wormholes";
            /** Lines */
            lines: string[];
        };
        /** StellarCartographySampleResponse */
        StellarCartographySampleResponse: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Entries */
            entries?: components["schemas"]["StellarCartographySampleEntry"][];
        };
        StellarCartographyTurnSummaryResponse: unknown;
        StoredTurnPerspectivesResponse: unknown;
        /**
         * TurnEnsureRequest
         * @description Parameters to ensure turn data exists in storage for a game and perspective slot.
         */
        TurnEnsureRequest: {
            /** Turn */
            turn: number;
            /** Perspective */
            perspective: number;
            /**
             * Username
             * @description Planets.nu account; required only when turn data is missing from storage and must be loaded from upstream.
             * @default
             */
            username: string;
            /** Password */
            password?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WarpWellCellsResponse */
        WarpWellCellsResponse: {
            /** Cells */
            cells: components["schemas"]["MapCellModel"][];
        };
        /**
         * WarpWellTypeParam
         * @enum {string}
         */
        WarpWellTypeParam: "normal" | "hyperjump";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_stored_games_games_get: {
        parameters: {
            query?: {
                includeDiagnostics?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stored_turn_perspectives_games__game_id__turns__turn_number__stored_perspectives_get: {
        parameters: {
            query?: {
                includeDiagnostics?: boolean;
            };
            header?: never;
            path: {
                game_id: number;
                turn_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoredTurnPerspectivesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stored_game_info_games__game_id__info_get: {
        parameters: {
            query?: {
                includeDiagnostics?: boolean;
            };
            header?: never;
            path: {
                game_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BffGameInfoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_game_info_games__game_id__info_post: {
        parameters: {
            query?: {
                includeDiagnostics?: boolean;
            };
            header?: never;
            path: {
                game_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GameInfoUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BffGameInfoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_load_all_turns_status_games__game_id__turns_load_all_status_get: {
        parameters: {
            query?: {
                username?: string;
                includeDiagnostics?: boolean;
            };
            header?: never;
            path: {
                game_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadAllTurnsStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_load_all_turns_stream_games__game_id__turns_load_all_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoadAllTurnsRequest"];
            };
        };
        responses: {
            /** @description NDJSON stream of progress, complete, and error events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "application/x-ndjson": components["schemas"]["LoadAllStreamProgressEvent"] | components["schemas"]["LoadAllStreamCompleteEvent"] | components["schemas"]["LoadAllStreamErrorEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_ensure_turn_games__game_id__turns_ensure_post: {
        parameters: {
            query?: {
                includeDiagnostics?: boolean;
            };
            header?: never;
            path: {
                game_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnEnsureRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BffTurnInfoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_warp_well_coordinate_in_well_games__game_id___perspective__turns__turn_number__concepts_warp_wells_coordinate_in_well_post: {
        parameters: {
            query?: {
                includeDiagnostics?: boolean;
            };
            header?: never;
            path: {
                game_id: number;
                perspective: number;
                turn_number: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoordinateInWarpWellRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoordinateInWarpWellResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_warp_well_cells_games__game_id___perspective__turns__turn_number__concepts_warp_wells_cells_get: {
        parameters: {
            query: {
                planet_id: number;
                well_type: components["schemas"]["WarpWellTypeParam"];
                includeDiagnostics?: boolean;
            };
            header?: never;
            path: {
                game_id: number;
                perspective: number;
                turn_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WarpWellCellsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stellar_cartography_sample_games__game_id___perspective__turns__turn_number__concepts_stellar_cartography_sample_get: {
        parameters: {
            query: {
                x: number;
                y: number;
                includeDiagnostics?: boolean;
            };
            header?: never;
            path: {
                game_id: number;
                perspective: number;
                turn_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StellarCartographySampleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stellar_cartography_turn_summary_games__game_id___perspective__turns__turn_number__concepts_stellar_cartography_summary_get: {
        parameters: {
            query?: {
                includeDiagnostics?: boolean;
            };
            header?: never;
            path: {
                game_id: number;
                perspective: number;
                turn_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StellarCartographyTurnSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
