/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/analytics/scores/inference": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scores Inference
         * @description Per-row military score build inference for the Scores analytic.
         */
        get: operations["get_scores_inference_analytics_scores_inference_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/scores/inference/table-stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scores Inference Table Stream
         * @description Stream build inference for all scoreboard rows on one NDJSON connection.
         */
        get: operations["get_scores_inference_table_stream_analytics_scores_inference_table_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/scores/inference/hull-catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scores Inference Hull Catalog
         * @description Master hull catalog and effective mask for one Scores inference row.
         */
        get: operations["get_scores_inference_hull_catalog_analytics_scores_inference_hull_catalog_get"];
        /**
         * Put Scores Inference Hull Catalog
         * @description Persist a user hull catalog mask override for one Scores inference row.
         */
        put: operations["put_scores_inference_hull_catalog_analytics_scores_inference_hull_catalog_put"];
        post?: never;
        /**
         * Delete Scores Inference Hull Catalog
         * @description Clear a user hull catalog mask override for one Scores inference row.
         */
        delete: operations["delete_scores_inference_hull_catalog_analytics_scores_inference_hull_catalog_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/scores/inference/global-pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scores Inference Global Pause
         * @description Whether scoreboard inference is globally paused for this turn scope.
         */
        get: operations["get_scores_inference_global_pause_analytics_scores_inference_global_pause_get"];
        put?: never;
        /**
         * Post Scores Inference Global Pause
         * @description Pause all scoreboard inference jobs for this turn scope.
         */
        post: operations["post_scores_inference_global_pause_analytics_scores_inference_global_pause_post"];
        /**
         * Delete Scores Inference Global Pause
         * @description Resume globally paused scoreboard inference for this turn scope.
         */
        delete: operations["delete_scores_inference_global_pause_analytics_scores_inference_global_pause_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Analytics
         * @description Return analytics available to the console.
         */
        get: operations["list_analytics_analytics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/{analytic_id}/table": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analytic Table
         * @description Tabular data scoped to the selected game, turn, and perspective.
         */
        get: operations["get_analytic_table_analytics__analytic_id__table_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/{analytic_id}/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analytic Map
         * @description Map data (nodes/edges). **base-map** returns planet nodes only (empty edges).
         *
         *     **connections** returns route pairs for the SPA to draw as edges on those nodes.
         *
         *     **stellar-cartography** returns overlay circles and wormhole graph geometry.
         *
         *     Nodes use fixed Cartesian coordinates (x, y). The SPA fetches base-map first, then
         *     enabled map analytics, and merges layers (see docs/design-connections-analytic.md).
         */
        get: operations["get_analytic_map_analytics__analytic_id__map_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * FlareConnectionMode
         * @description How flare-assisted routes are combined with direct warp-well reachability.
         * @enum {string}
         */
        FlareConnectionMode: "off" | "include" | "only";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InferenceHullCatalogMaskUpdateRequest */
        InferenceHullCatalogMaskUpdateRequest: {
            /** Enabledhullids */
            enabledHullIds: number[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_scores_inference_analytics_scores_inference_get: {
        parameters: {
            query: {
                gameId: number;
                turn: number;
                perspective: number;
                playerId: number;
                includeDiagnostics?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scores_inference_table_stream_analytics_scores_inference_table_stream_get: {
        parameters: {
            query: {
                gameId: number;
                turn: number;
                perspective: number;
                playerIds: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description NDJSON stream of tagged inference events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "application/x-ndjson": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scores_inference_hull_catalog_analytics_scores_inference_hull_catalog_get: {
        parameters: {
            query: {
                gameId: number;
                turn: number;
                perspective: number;
                playerId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_scores_inference_hull_catalog_analytics_scores_inference_hull_catalog_put: {
        parameters: {
            query: {
                gameId: number;
                turn: number;
                perspective: number;
                playerId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InferenceHullCatalogMaskUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_scores_inference_hull_catalog_analytics_scores_inference_hull_catalog_delete: {
        parameters: {
            query: {
                gameId: number;
                turn: number;
                perspective: number;
                playerId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scores_inference_global_pause_analytics_scores_inference_global_pause_get: {
        parameters: {
            query: {
                gameId: number;
                turn: number;
                perspective: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_scores_inference_global_pause_analytics_scores_inference_global_pause_post: {
        parameters: {
            query: {
                gameId: number;
                turn: number;
                perspective: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_scores_inference_global_pause_analytics_scores_inference_global_pause_delete: {
        parameters: {
            query: {
                gameId: number;
                turn: number;
                perspective: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_analytics_analytics_get: {
        parameters: {
            query?: {
                includeDiagnostics?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analytic_table_analytics__analytic_id__table_get: {
        parameters: {
            query: {
                gameId: number;
                turn: number;
                perspective: number;
                includeBuildInference?: boolean;
                includeDiagnostics?: boolean;
            };
            header?: never;
            path: {
                analytic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analytic_map_analytics__analytic_id__map_get: {
        parameters: {
            query: {
                gameId: number;
                turn: number;
                perspective: number;
                warpSpeed?: number;
                gravitonicMovement?: boolean;
                flareMode?: components["schemas"]["FlareConnectionMode"];
                /** @description Max hops (1–3) for mixed normal-move + flare paths; at least one hop must be a flare. Larger values add annulus pair candidates. Ignored when flareMode is off. */
                flareDepth?: number;
                /** @description When true, flare routes may include per-hop illustrativeRoute steps (Core). */
                includeIllustrativeRoutes?: boolean;
                includeDiagnostics?: boolean;
            };
            header?: never;
            path: {
                analytic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
