/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Analytics
         * @description Return analytics available to the console.
         */
        get: operations["list_analytics_analytics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/{analytic_id}/table": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analytic Table
         * @description Tabular data scoped to the selected game, turn, and perspective.
         */
        get: operations["get_analytic_table_analytics__analytic_id__table_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/{analytic_id}/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analytic Map
         * @description Map data (nodes/edges). **base-map** returns planet nodes only (empty edges).
         *
         *     **connections** returns route pairs for the SPA to draw as edges on those nodes.
         *
         *     **stellar-cartography** returns overlay circles and wormhole graph geometry.
         *
         *     Nodes use fixed Cartesian coordinates (x, y). The SPA fetches base-map first, then
         *     enabled map analytics, and merges layers (see docs/design-connections-analytic.md).
         */
        get: operations["get_analytic_map_analytics__analytic_id__map_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * FlareConnectionMode
         * @description How flare-assisted routes are combined with direct warp-well reachability.
         * @enum {string}
         */
        FlareConnectionMode: "off" | "include" | "only";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_analytics_analytics_get: {
        parameters: {
            query?: {
                includeDiagnostics?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analytic_table_analytics__analytic_id__table_get: {
        parameters: {
            query: {
                gameId: number;
                turn: number;
                perspective: number;
                includeDiagnostics?: boolean;
            };
            header?: never;
            path: {
                analytic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analytic_map_analytics__analytic_id__map_get: {
        parameters: {
            query: {
                gameId: number;
                turn: number;
                perspective: number;
                warpSpeed?: number;
                gravitonicMovement?: boolean;
                flareMode?: components["schemas"]["FlareConnectionMode"];
                /** @description Max hops (1–3) for mixed normal-move + flare paths; at least one hop must be a flare. Larger values add annulus pair candidates. Ignored when flareMode is off. */
                flareDepth?: number;
                /** @description When true, flare routes may include per-hop illustrativeRoute steps (Core). */
                includeIllustrativeRoutes?: boolean;
                includeDiagnostics?: boolean;
            };
            header?: never;
            path: {
                analytic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
