/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Analytics
         * @description Return analytics available to the console.
         */
        get: operations["list_analytics_analytics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/{analytic_id}/table": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analytic Table
         * @description Tabular data scoped to the selected game, turn, and perspective.
         */
        get: operations["get_analytic_table_analytics__analytic_id__table_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/{analytic_id}/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analytic Map
         * @description Map data (nodes/edges). **base-map** returns planet nodes only (empty edges).
         *
         *     **connections** returns route pairs for the SPA to draw as edges on those nodes.
         *
         *     **stellar-cartography** returns overlay circles and wormhole graph geometry.
         *
         *     Nodes use fixed Cartesian coordinates (x, y). The SPA fetches base-map first, then
         *     enabled map analytics, and merges layers (see docs/design-connections-analytic.md).
         */
        get: operations["get_analytic_map_analytics__analytic_id__map_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagnostics/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Recent Diagnostics
         * @description Return entries captured when handlers were invoked with ``includeDiagnostics``.
         */
        get: operations["get_recent_diagnostics_diagnostics_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Stored Games
         * @description Return game ids present under store path `games` (next-hop segment names).
         *
         *     Route: **GET /games** on the BFF app; **GET /bff/games** when the BFF is mounted at `/bff`.
         *
         *     Uses the same shallow enumeration as GET /api/v1/store/games?view=shallow.
         */
        get: operations["list_stored_games_games_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/turns/{turn_number}/stored-perspectives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stored Turn Perspectives
         * @description Return perspective slots that already have turn data in storage (no Planets.nu).
         */
        get: operations["get_stored_turn_perspectives_games__game_id__turns__turn_number__stored_perspectives_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stored Game Info
         * @description Return game info already in storage (no Planets.nu refresh).
         */
        get: operations["get_stored_game_info_games__game_id__info_get"];
        put?: never;
        /**
         * Post Game Info
         * @description Refresh game info from Planets.nu (`refresh`); returns updated `GameInfo`.
         */
        post: operations["post_game_info_games__game_id__info_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/turns/ensure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Ensure Turn
         * @description Ensure turn data exists in storage; fetch from Planets.nu when absent.
         */
        post: operations["post_ensure_turn_games__game_id__turns_ensure_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/{perspective}/turns/{turn_number}/concepts/warp-wells/coordinate-in-well": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Warp Well Coordinate In Well
         * @description Turn-scoped warp-well point test via ``CoreClient`` (shared handler with Core REST).
         */
        post: operations["post_warp_well_coordinate_in_well_games__game_id___perspective__turns__turn_number__concepts_warp_wells_coordinate_in_well_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/{perspective}/turns/{turn_number}/concepts/warp-wells/cells": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Warp Well Cells
         * @description Turn-scoped warp-well cells via ``CoreClient`` (shared handler with Core REST).
         */
        get: operations["get_warp_well_cells_games__game_id___perspective__turns__turn_number__concepts_warp_wells_cells_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shell/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Shell Bootstrap
         * @description Return shell-oriented server config for the SPA (e.g. optional default game id).
         */
        get: operations["get_shell_bootstrap_shell_bootstrap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BffGameInfoResponse: unknown;
        BffTurnInfoResponse: unknown;
        /** CoordinateInWarpWellRequest */
        CoordinateInWarpWellRequest: {
            /** Planet Id */
            planet_id: number;
            /** Map X */
            map_x: number;
            /** Map Y */
            map_y: number;
            well_type: components["schemas"]["WarpWellTypeParam"];
        };
        /** CoordinateInWarpWellResponse */
        CoordinateInWarpWellResponse: {
            /** Inside */
            inside: boolean;
        };
        /**
         * FlareConnectionMode
         * @description How flare-assisted routes are combined with direct warp-well reachability.
         * @enum {string}
         */
        FlareConnectionMode: "off" | "include" | "only";
        /**
         * GameInfoUpdateOperation
         * @enum {string}
         */
        GameInfoUpdateOperation: "refresh";
        /** GameInfoUpdateRequest */
        GameInfoUpdateRequest: {
            operation: components["schemas"]["GameInfoUpdateOperation"];
            /** Params */
            params: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MapCellModel */
        MapCellModel: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** Message */
        Message: {
            /** Id */
            id: number;
            /** Ownerid */
            ownerid: number;
            messagetype: components["schemas"]["MessageType"];
            /** Headline */
            headline: string;
            /** Body */
            body: string;
            /** Target */
            target: number;
            /** Turn */
            turn: number;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * MessageType
         * @enum {integer}
         */
        MessageType: -1 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21;
        /** Player */
        Player: {
            /** Id */
            id: number;
            /** Status */
            status: number;
            /** Statusturn */
            statusturn: number;
            /** Accountid */
            accountid: number;
            /** Username */
            username: string;
            /** Email */
            email: string;
            /** Raceid */
            raceid: number;
            /** Teamid */
            teamid: number;
            /** Prioritypoints */
            prioritypoints: number;
            /** Joinrank */
            joinrank: number;
            /** Finishrank */
            finishrank: number;
            /** Turnjoined */
            turnjoined: number;
            /** Turnready */
            turnready: boolean;
            /** Turnreadydate */
            turnreadydate: string;
            /** Turnstatus */
            turnstatus: number;
            /** Turnsmissed */
            turnsmissed: number;
            /** Turnsmissedtotal */
            turnsmissedtotal: number;
            /** Turnsholiday */
            turnsholiday: number;
            /** Turnsearly */
            turnsearly: number;
            /** Turn */
            turn: number;
            /** Timcontinuum */
            timcontinuum: number;
            /** Savekey */
            savekey: string;
            /** Tutorialid */
            tutorialid: number;
            /** Tutorialtaskid */
            tutorialtaskid: number;
            /** Megacredits */
            megacredits: number;
            /** Duranium */
            duranium: number;
            /** Tritanium */
            tritanium: number;
            /** Molybdenum */
            molybdenum: number;
            /** Leagueteamid */
            leagueteamid: number;
            /** Activehulls */
            activehulls: string;
            /** Activeadvantages */
            activeadvantages: string;
            /** Activeengines */
            activeengines: string;
            /** Activebeams */
            activebeams: string;
            /** Activetorps */
            activetorps: string;
        };
        ShellBootstrapResponse: unknown;
        StoredTurnPerspectivesResponse: unknown;
        /**
         * TurnEnsureRequest
         * @description Parameters to ensure turn data exists in storage for a game and perspective slot.
         */
        TurnEnsureRequest: {
            /** Turn */
            turn: number;
            /** Perspective */
            perspective: number;
            /**
             * Username
             * @description Planets.nu account; required only when turn data is missing from storage and must be loaded from upstream.
             * @default
             */
            username: string;
            /** Password */
            password?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VcrSide */
        VcrSide: {
            /** Id */
            id: number;
            /** Vcrid */
            vcrid: number;
            /** Objectid */
            objectid: number;
            /** Name */
            name: string;
            /** Side */
            side: number;
            /** Beamcount */
            beamcount: number;
            /** Launchercount */
            launchercount: number;
            /** Baycount */
            baycount: number;
            /** Hullid */
            hullid: number;
            /** Beamid */
            beamid: number;
            /** Torpedoid */
            torpedoid: number;
            /** Shield */
            shield: number;
            /** Damage */
            damage: number;
            /** Crew */
            crew: number;
            /** Mass */
            mass: number;
            /** Raceid */
            raceid: number;
            /** Beamkillbonus */
            beamkillbonus: number;
            /** Beamchargerate */
            beamchargerate: number;
            /** Torpchargerate */
            torpchargerate: number;
            /** Torpmisspercent */
            torpmisspercent: number;
            /** Crewdefensepercent */
            crewdefensepercent: number;
            /** Torpedos */
            torpedos: number;
            /** Fighters */
            fighters: number;
            /** Temperature */
            temperature: number;
            /** Hasstarbase */
            hasstarbase: boolean;
        };
        /** WarpWellCellsResponse */
        WarpWellCellsResponse: {
            /** Cells */
            cells: components["schemas"]["MapCellModel"][];
        };
        /**
         * WarpWellTypeParam
         * @enum {string}
         */
        WarpWellTypeParam: "normal" | "hyperjump";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_analytics_analytics_get: {
        parameters: {
            query?: {
                includeDiagnostics?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analytic_table_analytics__analytic_id__table_get: {
        parameters: {
            query: {
                gameId: number;
                turn: number;
                perspective: number;
                includeDiagnostics?: boolean;
            };
            header?: never;
            path: {
                analytic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analytic_map_analytics__analytic_id__map_get: {
        parameters: {
            query: {
                gameId: number;
                turn: number;
                perspective: number;
                warpSpeed?: number;
                gravitonicMovement?: boolean;
                flareMode?: components["schemas"]["FlareConnectionMode"];
                /** @description Max hops (1–3) for mixed normal-move + flare paths; at least one hop must be a flare. Larger values add annulus pair candidates. Ignored when flareMode is off. */
                flareDepth?: number;
                /** @description When true, flare routes may include per-hop illustrativeRoute steps (Core). */
                includeIllustrativeRoutes?: boolean;
                includeDiagnostics?: boolean;
            };
            header?: never;
            path: {
                analytic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recent_diagnostics_diagnostics_recent_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_stored_games_games_get: {
        parameters: {
            query?: {
                includeDiagnostics?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stored_turn_perspectives_games__game_id__turns__turn_number__stored_perspectives_get: {
        parameters: {
            query?: {
                includeDiagnostics?: boolean;
            };
            header?: never;
            path: {
                game_id: number;
                turn_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoredTurnPerspectivesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stored_game_info_games__game_id__info_get: {
        parameters: {
            query?: {
                includeDiagnostics?: boolean;
            };
            header?: never;
            path: {
                game_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BffGameInfoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_game_info_games__game_id__info_post: {
        parameters: {
            query?: {
                includeDiagnostics?: boolean;
            };
            header?: never;
            path: {
                game_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GameInfoUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BffGameInfoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_ensure_turn_games__game_id__turns_ensure_post: {
        parameters: {
            query?: {
                includeDiagnostics?: boolean;
            };
            header?: never;
            path: {
                game_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnEnsureRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BffTurnInfoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_warp_well_coordinate_in_well_games__game_id___perspective__turns__turn_number__concepts_warp_wells_coordinate_in_well_post: {
        parameters: {
            query?: {
                includeDiagnostics?: boolean;
            };
            header?: never;
            path: {
                game_id: number;
                perspective: number;
                turn_number: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoordinateInWarpWellRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoordinateInWarpWellResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_warp_well_cells_games__game_id___perspective__turns__turn_number__concepts_warp_wells_cells_get: {
        parameters: {
            query: {
                planet_id: number;
                well_type: components["schemas"]["WarpWellTypeParam"];
                includeDiagnostics?: boolean;
            };
            header?: never;
            path: {
                game_id: number;
                perspective: number;
                turn_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WarpWellCellsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shell_bootstrap_shell_bootstrap_get: {
        parameters: {
            query?: {
                includeDiagnostics?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShellBootstrapResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
